title: "Chris Crawford"
description: ""
baseurl: ""

sass:
  style: compressed
  sass_dir: assets/css

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/posts/page:num"

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chris"
